# Generated by Django 4.2.14 on 2024-07-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=50)),
                ('sal', models.CharField(max_length=50)),
                ('deptno', models.CharField(max_length=50)),
            ],
        ),
    ]
